### PR TITLE
Add more scopes to the tree-sitter grammar

### PR DESCRIPTION
**Pull request by Ben3eeE**
🚨 WIP 🚨 

**TODO:**
- [ ] Investigate open issues https://github.com/atom/language-c/pull/303#issuecomment-435459813
- [x] Scope punctuation in C

Refs https://github.com/atom/atom/issues/18347#issuecomment-434970725

Depends on: https://github.com/atom/atom/pull/18382

Fixes: https://github.com/atom/language-c/issues/297
Fixes: https://github.com/atom/language-c/issues/296
Fixes: https://github.com/atom/language-c/issues/295
Fixes: https://github.com/atom/language-c/issues/294
Fixes: https://github.com/atom/language-c/issues/293
Fixes: https://github.com/atom/language-c/issues/291

/cc: @maxbrunsfeld

### CODE REVIEW

**Comment by thomasjo** [comment]
@Ben3eeE Haven't had time to check this myself yet, but does this cause any false positives with C++ template expressions? E.g. `template <typename T>`, `template <std::vector<T>>`, and so forth? For those expressions the brackets should not be marked as operators.

**Comment by Ben3eeE** [comment]
@thomasjo Thanks for pointing that out. It's entirely possible that it will conflict with template expressions. I haven't tested this myself yet actually. Just editing through the web editor 🙂 

I will take a look at this as soon as I can. Are there any other examples you can think of?

**Comment by thomasjo** [comment]
@Ben3eeE Can't think of anything else right now, but I'll have a "quick" scan through the language specification later. Will let you know if I find anything exotic :grin:

**Comment by Ben3eeE** [comment]
@thomasjo After https://github.com/atom/atom/pull/18382 is merged this PR as it is now will work and not conflict with template expressions.

TextMate still scopes `>` and `<` in template expressions as `keyword.operator.comparison` so we might want to just leave it scoped incorrectly to not break highlighting of `<` and `>` in themes.

@maxbrunsfeld Do you think we should scope `>` and `<` as `keyword.operator` in template expressions to keep the highlighting the same as textmate?

**Comment by maxbrunsfeld** [comment]
> Do you think we should scope > and < as keyword.operator in template expressions to keep the highlighting the same as textmate?

I think we shouldn't; I'd prefer to either leave them as unscoped, or scope them in a way that's similar to the `(`, `)`, `[`, and `]` characters.

**Comment by Ben3eeE** [comment]
Seems like we don't have any `punctuation` scopes in the tree-sitter grammar at all. I will sync it up with textmate and correct this/other bugs 👍 

Thanks so much for taking a look at this PR @thomasjo it made us notice the bug in atom core and fix up the scopes more 💯

**Comment by Ben3eeE** [comment]
We have a bunch of opened issues from @chbk regarding `punctuation` scopes but all are with the textmate grammar. I think it will make sense to fix these for the tree-sitter grammar.

**Comment by 50Wliu** [comment]
Another agreement with @maxbrunsfeld. We shouldn't let old bugs with the TextMate grammars affect Tree-sitter.

**Comment by Ben3eeE** [comment]
@maxbrunsfeld I took a look at the open issues we have here to see if I could improve further. Some of these parse incorrectly with tree-sitter. I didn't check if any of these are valid reports. Just blindly assuming that they are.

https://github.com/atom/language-c/issues/233
https://github.com/atom/language-c/issues/260
https://github.com/atom/language-c/issues/267
https://github.com/atom/language-c/issues/273
https://github.com/atom/language-c/issues/280
https://github.com/atom/language-c/issues/153
https://github.com/atom/language-c/issues/246
We could solve https://github.com/atom/language-c/issues/246 with a regular expression. We could parse this in tree-sitter like `sizeof`. Searching around for this I found https://en.cppreference.com/w/cpp/language/alignof which has the example code:
```
struct alignas(64) Empty64 {};
 ```
alignas(64) is parsed as a `type_identifier`


Issues we can solve that are also an issue in tree-sitter:
https://github.com/atom/language-c/issues/240
https://github.com/atom/language-c/issues/177

**Comment by maxbrunsfeld** [comment]
I think let's get this into today's hotfix as-is. We can circle back and fix the parsing issues that you mentioned in another pass.

**Pull request merged**
