### PR TITLE
Adding .C as a file extension for C++ files

### LINKED ISSUE #94: Add .C to the file extensions
Our C++ project is using `.C` as a file extension.
Could this be added to the list?

### PR DESCRIPTION
**Pull request by andrsd**
Closes #94

### CODE REVIEW

**Comment by thomasjo** [comment]
I'm afraid we can't do this for two reasons;
 1. `.c` belongs to the C programming language, and not C++.
 2. Because `.c` is tied to C it's also defined in the [grammar file `c.cson`](https://github.com/atom/language-c/blob/v0.49.0/grammars/c.cson#L3).

You can work around this on your end however by leveraging the configuration option `core.customFileTypes`. Since the documentation for that feature is not yet live on atom.io, please see
https://github.com/atom/docs/blob/6e8baeecaf939426e66ee960c168cf27117215ef/book/02-using-atom/sections/06-customizing.asc#customizing-language-recognition.

**Comment by thomasjo** [comment]
@andrsd Thanks for contributing by the way! Much appreciated :bow:

**Comment by andrsd** [comment]
@thomasjo `.c` (little c) is for C, however, I added '.C' (big c) for C++. Are you saying the file extensions are case insensitive (because of case-insensitive file systems on some operation systems) ?

**Comment by thomasjo** [comment]
Correct.

**Comment by andrsd** [comment]
Ok, then out of curiosity 'h' is listed in both c.cson and c++.cson. Would not that create a problem as well?

Also, thanks for the tip how to fix it locally on my machine.

**Comment by thomasjo** [comment]
> Ok, then out of curiosity 'h' is listed in both c.cson and c++.cson. Would not that create a problem as well?

Yeah, and it does cause problems (sort of); the C grammar always wins (shortest name). The only time the C++ grammar wins is if the [`firstLineMatch`](https://github.com/atom/language-c/blob/master/grammars/c%2B%2B.cson#L20) kicks in. Only reason it's listed under the C++ grammar as well is because there is widespread usage of the `.h` extension for both C++ and C (very unfortunate if you ask me, but it's not something that can be fixed).

**Comment by andrsd** [comment]
Interesting. Well, life is not perfect ;-)

**Comment by dschwen** [comment]
Is there a way for the user to override this maybe?

**Comment by Arcanemagus** [comment]
You can override this following the instructions for [Customizing Language Recognition](https://flight-manual.atom.io/using-atom/sections/basic-customization/#customizing-language-recognition).

Locking this 5 year old issue, if you have a problem with this package please file a new issue.

**Pull request closed without merging**
