### PR TITLE
Highlight div_t

### PR DESCRIPTION
**Pull request by nabeelomer**
Partially fixes https://github.com/atom/language-c/issues/126.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Hi @nabeelomer, can you elaborate on how this only "partially fixes" #126?  Is there another place that needs changes?

**Comment by nabeelomer** [comment]
@50Wliu I'm extremely embarrassed. I read the issue wrong. I thought both `div_t` and the function `div` need to be highlighted.

**Comment by 50Wliu** [comment]
It looks like `div_t` only exists in C++ - can you please move this to the C++ file instead?  Thanks.

**Comment by M4GNV5** [comment]
Nope, `div` is part of the C standard, here's the man page from section 3: http://man7.org/linux/man-pages/man3/div.3.html

however maybe these should so be added: `ldiv_t`, `lldiv_t` and `imaxdiv_t`

**Comment by 50Wliu** [comment]
Yes, it looks like I was mistaken.  I will merge this now - @nabeelomer or @M4GNV5 feel free to create a new PR adding the other types.

**Pull request merged**
