### PR TITLE
fix style

### PR DESCRIPTION
**Pull request by dd1994**

### CODE REVIEW

**Comment by izuzak** [comment]
@dd1994 Since this is about style -- can you share some links which would argue in favor of this change? I.e. some discussions which confirm that this style is what most users use and expect? I think most discussions around questions like this only agreed that it's good to be consistent in whatever style the project uses.

**Comment by dd1994** [comment]
@izuzak because other snippets in this repo, like `main`, `for loop`,  `while`, `function`...  is in this style,
so it's good to be consistent.

**Comment by izuzak** [comment]
I'm not sure I understand. Can you clarify which of those snippets you listed has some text after the closing `}` ? And what would be the alternate version for one of those snippets, e.g. `function`?

**Comment by dd1994** [comment]
@izuzak sorry for my poor English, I'm not a native speaker...
like: https://github.com/atom/language-c/blob/master/snippets/language-c.cson#L68

expand to:
```c
int name(/* arguments */) {
  /* code */
  return 0;
}
```
but not
```c
int name(/* arguments */)
{
  /* code */
  return 0;
}

```

and `while` https://github.com/atom/language-c/blob/master/snippets/language-c.cson#L32
expand to:
```c
while (/* condition */) {
  /* code */
}
```
not
```c
while (/* condition */)
{
  /* code */
}
```
hope that's clear...

**Comment by izuzak** [comment]
@dd1994 Thanks for explaining. The parts you are referring to are related to the line with the opening `{`, not the line with the closing `}`, which is what this PR is about. Does that clarify?

**Comment by dd1994** [comment]
@izuzak yes

**Comment by dd1994** [comment]
just like snipptes in language-javascript: https://github.com/atom/language-javascript/blob/master/snippets/language-javascript.cson#L17

**Comment by izuzak** [comment]
Yep, I was just looking at those and thinking the same thing. :+1: Let's change these as well then -- thanks for opening a PR and discussing.

**Pull request merged**
